### ISSUE TITLE
Available on clojars?

### ISSUE THREAD

**Issue by WorldsEndless** [damienstanton/stanford-corenlp#18]
the readme doesn't include simple install instructions (e.g. for Leiningen), and searching clojars for stanford-corenlp actually has a lot of results. Is there an easy clojar install for stanford-corenlp? That would be trememdously useful at the top of the readme.

**Comment by andrewmcloud** [comment]
@WorldsEndless currently this library is not on clojars. To install and use as a dependency, clone the project, run `lein install` from within the project directory to install as a local dependency in your ~/.m2 directory. Use [corenlp "3.6.0a"] in your project.clj.

@damienstanton can we put this on clojars?

**Comment by WorldsEndless** [comment]
@andrewmcloud Yeah, that's how I installed it. A bit unconventional by modern Clojure standards, though. It would be great to have this on Clojars (there are a bunch of spin-offs, but the latest version would be nice)

**Comment by damienstanton** [comment]
Fair point. Since this is alpha-ish I was hesitant to put it on Clojars. But it looks like that will only help people with installing and contributing, so I'll get it done 👍 

Just need to work out some kinks on my dev laptop with gpg signing and I'll update the readme when it's published.

**Comment by andrewmcloud** [comment]
@damienstanton if you are using a Debian distro: try adding `use-agent` to `~/.gnupg/gpg.conf`. You can test with `gpg --quiet --batch --decrypt ~/.lein/credentials.clj.gpg`

**Comment by damienstanton** [comment]
Sorry for the delay - it's been published to clojars and the readme has been updated accordingly. If there are any issues please let me know, this is my first time deploying to the site 🎉

**Comment by andrewmcloud** [comment]
👍
